### ISSUE TITLE
Problems to deploy microservices: authentication, reccomendation, payment

### ISSUE THREAD

**Issue by danv006** [aws-samples/observability-with-amazon-opensearch#55]
After deploy the App to run Workshop OpenSearch Observability these microservices don't start with error on pod logs: TypeError: __init__() got an unexpected keyword argument 'method_whitelist'.

**Comment by rafael-gumiero** [comment]
Hello @danv006, Thanks for notifying us of this issue! I would like to check if you have the log of this start because I couldn't reproduce it during my test.

**Comment by rafael-gumiero** [comment]
@danv006 Now I managed to reproduce and the problem is in the method_whitelist that was deprecated. I'm updating the dependencies and until the end of the day I merge the fix.

**Comment by rafael-gumiero** [comment]
Fixed the problem! #56
