### ISSUE TITLE
Refactor the workshop to use Amazon OpenSearch Ingestion Service

### ISSUE THREAD

**Issue by mishavay-aws** [aws-samples/observability-with-amazon-opensearch#58]
Refactor the workshop to use Amazon OpenSearch Ingestion Service for ingesting logs, telemetry, and traces from the workshop application.  Incorporate CFT and application changes to simplify installation, configuration and delivery of the workshop.

**Comment by rafael-gumiero** [comment]
Resolved through PR #59.
